---
name: CI
on:
  push:
    branches:
      - master
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOWNLOAD_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  DOWNLOAD_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  UPLOAD_BUCKET: ${{ secrets.UPLOAD_BUCKET }}
  UPLOAD_REGION: ${{ secrets.UPLOAD_REGION }}
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            uuid:
              - uuid.txt
    outputs:
      uuid: ${{ steps.filter.outputs.uuid }}
  build:
    needs: changes
    if: ${{ needs.changes.outputs.uuid == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build version
        run: ./build.sh -A config.system.build.upload -o upload
      - name: Upload version
        run: ./upload
